const babaQuotes = [
      { "id": 1, "quote": "Don’t worry, be happy.", "author": "Meher Baba" },
      { "id": 2, "quote": "Love has to spring spontaneously from within.", "author": "Meher Baba" },
      { "id": 3, "quote": "True love is no game of the faint-hearted and the weak; it is born of strength and understanding.", "author": "Meher Baba" },
      { "id": 4, "quote": "The mind and intellect are like plain glass. You see through them, but they color the vision.", "author": "Meher Baba" },
      { "id": 5, "quote": "Happiness lies in making others happy, in forsaking self-interest to bring joy to others.", "author": "Meher Baba" },
      { "id": 6, "quote": "The path of love is the only path that can lead man to salvation and ultimate freedom.", "author": "Meher Baba" },
      { "id": 7, "quote": "Real happiness lies in making others happy.", "author": "Meher Baba" },
      { "id": 8, "quote": "I am the one to be desired, sought and loved.", "author": "Meher Baba" },
      { "id": 9, "quote": "Do your best. Then, don’t worry; be happy in My love. I will help you.", "author": "Meher Baba" },
      { "id": 10, "quote": "God cannot be explained. He can only be lived.", "author": "Meher Baba" },
      { "id": 11, "quote": "To love God in the most practical way is to love our fellow beings.", "author": "Meher Baba" },
      { "id": 12, "quote": "The satisfaction of one's physical needs and cravings does not give happiness.", "author": "Meher Baba" },
      { "id": 13, "quote": "The soul is God.", "author": "Meher Baba" },
      { "id": 14, "quote": "The mind cannot know God. Only the heart knows the secret of divine love.", "author": "Meher Baba" },
      { "id": 15, "quote": "The greatest law of God is love, and the lover seeks no reward for love.", "author": "Meher Baba" },
      { "id": 16, "quote": "Life is a mighty joke.", "author": "Meher Baba" },
      { "id": 17, "quote": "When the mind soars in pursuit of the things conceived in space, it pursues emptiness.", "author": "Meher Baba" },
      { "id": 18, "quote": "The purpose of life is to realize God within ourselves.", "author": "Meher Baba" },
      { "id": 19, "quote": "Divine love is boundless and infinite.", "author": "Meher Baba" },
      { "id": 20, "quote": "The only Real Existence is that of the One and only God Who is the Self in every finite self.", "author": "Meher Baba" },
      { "id": 21, "quote": "The universe is the outcome of imagination.", "author": "Meher Baba" },
      { "id": 22, "quote": "The Infinite alone exists.", "author": "Meher Baba" },
      { "id": 23, "quote": "Man is a prisoner of his own desires.", "author": "Meher Baba" },
      { "id": 24, "quote": "True love can only arise when self is obliterated.", "author": "Meher Baba" },
      { "id": 25, "quote": "It is impossible to achieve freedom from fear, anger, and hate, unless the mind first achieves freedom from desires.", "author": "Meher Baba" },
      { "id": 26, "quote": "Do not seek to possess anything but God.", "author": "Meher Baba" },
      { "id": 27, "quote": "Love God and find Him within – the only treasure worth finding.", "author": "Meher Baba" },
      { "id": 28, "quote": "There is no end to the unfoldment of love.", "author": "Meher Baba" },
      { "id": 29, "quote": "Live more and more in the present, which is ever beautiful and stretches away beyond the limits of the past and the future.", "author": "Meher Baba" },
      { "id": 30, "quote": "You have to lose yourself to find yourself.", "author": "Meher Baba" },
      { "id": 31, "quote": "The most helpful attitude is one of love and selflessness.", "author": "Meher Baba" },
      { "id": 32, "quote": "He who does not love is as good as dead.", "author": "Meher Baba" },
      { "id": 33, "quote": "Words that proceed from the depths of truth and love have power.", "author": "Meher Baba" },
      { "id": 34, "quote": "Do not give in to low desires, for they turn you away from the path.", "author": "Meher Baba" },
      { "id": 35, "quote": "I am the Ancient One, come to redeem man from his bondage of ignorance and help him realize his true self.", "author": "Meher Baba" },
      { "id": 36, "quote": "Spirituality is not renunciation of life. It is the realization of life.", "author": "Meher Baba" },
      { "id": 37, "quote": "The mind creates its own imprisonment, but the heart provides the key to freedom.", "author": "Meher Baba" },
      { "id": 38, "quote": "God alone is Real and everything else is false.", "author": "Meher Baba" },
      { "id": 39, "quote": "God does not listen to the language of the mind. He responds to the language of the heart.", "author": "Meher Baba" },
      { "id": 40, "quote": "The lover surrenders to the beloved. Such is love that never dies.", "author": "Meher Baba" },
      { "id": 41, "quote": "The highest aim of man is to realize the infinite potential of love.", "author": "Meher Baba" },
      { "id": 42, "quote": "When you recognize your own ignorance, you can see the light of truth.", "author": "Meher Baba" },
      { "id": 43, "quote": "Love alone is capable of uniting human beings in such a way as to complete and fulfill them.", "author": "Meher Baba" },
      { "id": 44, "quote": "To lose the limited self is to find the unlimited Self.", "author": "Meher Baba" },
      { "id": 45, "quote": "Live and help others to live.", "author": "Meher Baba" },
      { "id": 46, "quote": "Only in silence can the divine speak to the heart.", "author": "Meher Baba" },
      { "id": 47, "quote": "Do not become attached to anything, for everything is temporary.", "author": "Meher Baba" },
      { "id": 48, "quote": "Infinite patience brings immediate results.", "author": "Meher Baba" },
      { "id": 49, "quote": "Do not be anxious about what you cannot change. It will pass.", "author": "Meher Baba" },
      { "id": 50, "quote": "You can only give what you have, so fill your heart with love and give that love to others.", "author": "Meher Baba" },
      { "id": 51, "quote": "The goal of life is not to possess, but to realize your own divinity.", "author": "Meher Baba" },
      { "id": 52, "quote": "Man must die to his lower self to be born in God.", "author": "Meher Baba" },
      { "id": 53, "quote": "The heart of man must beat with the rhythm of divine love.", "author": "Meher Baba" },
      { "id": 54, "quote": "The only lasting happiness is the happiness of the heart.", "author": "Meher Baba" },
      { "id": 55, "quote": "Love is the only reality and it is not a mere sentiment. It is the ultimate truth that lies at the heart of creation.", "author": "Meher Baba" },
      { "id": 56, "quote": "You and I are not we but One.", "author": "Meher Baba" },
      { "id": 57, "quote": "The lover desires no reward for his love. He is content to love for love's sake.", "author": "Meher Baba" },
      { "id": 58, "quote": "Man has no choice but to love.", "author": "Meher Baba" },
      { "id": 59, "quote": "Love and forgiveness go hand in hand.", "author": "Meher Baba" },
      { "id": 60, "quote": "The greatest treasure is within, not outside.", "author": "Meher Baba" },
      { "id": 61, "quote": "When you love God, you no longer love anything else.", "author": "Meher Baba" },
      { "id": 62, "quote": "Suffering brings real happiness. Real happiness comes from renunciation of desires.", "author": "Meher Baba" },
      { "id": 63, "quote": "True love is pure and unconditional.", "author": "Meher Baba" },
      { "id": 64, "quote": "All that is real is given and received in silence.", "author": "Meher Baba" },
      { "id": 65, "quote": "Let go of your ego and you will be free.", "author": "Meher Baba" },
      { "id": 66, "quote": "Divine love burns in the heart of the true seeker.", "author": "Meher Baba" },
      { "id": 67, "quote": "I am nearer to you than your own breath.", "author": "Meher Baba" },
      { "id": 68, "quote": "He who loves God becomes God.", "author": "Meher Baba" },
      { "id": 69, "quote": "The greater the love, the less the ego.", "author": "Meher Baba" },
      { "id": 70, "quote": "When you surrender to God, He takes care of everything.", "author": "Meher Baba" },
      { "id": 71, "quote": "Love me so that you may know yourself.", "author": "Meher Baba" },
      { "id": 72, "quote": "True humility is strength.", "author": "Meher Baba" },
      { "id": 73, "quote": "The lover sees the Beloved everywhere and in everything.", "author": "Meher Baba" },
      { "id": 74, "quote": "Love never asks for anything in return.", "author": "Meher Baba" },
      { "id": 75, "quote": "He who loses himself in God finds himself in everyone.", "author": "Meher Baba" },
      { "id": 76, "quote": "The veil that covers the Truth is ignorance.", "author": "Meher Baba" },
      { "id": 77, "quote": "I am the eternal Beloved.", "author": "Meher Baba" },
      { "id": 78, "quote": "The universe is within you.", "author": "Meher Baba" },
      { "id": 79, "quote": "Love is the only freedom from attachment.", "author": "Meher Baba" },
      { "id": 80, "quote": "The more you love, the closer you come to me.", "author": "Meher Baba" },
      { "id": 81, "quote": "To love is to lose yourself in the Beloved.", "author": "Meher Baba" },
      { "id": 82, "quote": "Silence is the language of God.", "author": "Meher Baba" },
      { "id": 83, "quote": "Be calm in the face of all that happens and love Me more.", "author": "Meher Baba" },
      { "id": 84, "quote": "The heart that loves is always young.", "author": "Meher Baba" },
      { "id": 85, "quote": "Love is its own reward.", "author": "Meher Baba" },
      { "id": 86, "quote": "No one is lost. Everyone will eventually come to Me.", "author": "Meher Baba" },
      { "id": 87, "quote": "I am the Ocean of Love.", "author": "Meher Baba" },
      { "id": 88, "quote": "The spiritual path is like a razor's edge.", "author": "Meher Baba" },
      { "id": 89, "quote": "All paths lead to Me.", "author": "Meher Baba" },
      { "id": 90, "quote": "The only solution is love.", "author": "Meher Baba" },
      { "id": 91, "quote": "There is nothing greater than love.", "author": "Meher Baba" },
      { "id": 92, "quote": "I am eternally free.", "author": "Meher Baba" },
      { "id": 93, "quote": "The search for God is the search for the Self.", "author": "Meher Baba" },
      { "id": 94, "quote": "The soul is on a journey to realize its true self.", "author": "Meher Baba" },
      { "id": 95, "quote": "Love transcends all barriers.", "author": "Meher Baba" },
      { "id": 96, "quote": "Be absorbed in the One, and all else will be added unto you.", "author": "Meher Baba" },
      { "id": 97, "quote": "The Beloved is nearer than the nearest.", "author": "Meher Baba" },
      { "id": 98, "quote": "Serve others selflessly and you serve Me.", "author": "Meher Baba" },
      { "id": 99, "quote": "Everything exists within Me, and I exist within everything.", "author": "Meher Baba" },
      { "id": 100, "quote": "Only love dispels fear.", "author": "Meher Baba" }
    ]

  